cmd_/home/yochen0125/drv_practice/chrdev/chrdev.o := arm-linux-gnueabihf-gcc -Wp,-MD,/home/yochen0125/drv_practice/chrdev/.chrdev.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/9/include -I./arch/arm/include -I./arch/arm/include/generated/uapi -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types  -DMODULE  -DKBUILD_BASENAME='"chrdev"'  -DKBUILD_MODNAME='"chrdev"' -c -o /home/yochen0125/drv_practice/chrdev/.tmp_chrdev.o /home/yochen0125/drv_practice/chrdev/chrdev.c

source_/home/yochen0125/drv_practice/chrdev/chrdev.o := /home/yochen0125/drv_practice/chrdev/chrdev.c

deps_/home/yochen0125/drv_practice/chrdev/chrdev.o := \

/home/yochen0125/drv_practice/chrdev/chrdev.o: $(deps_/home/yochen0125/drv_practice/chrdev/chrdev.o)

$(deps_/home/yochen0125/drv_practice/chrdev/chrdev.o):
